config/routes.rb
CuriousRailsGirls::Application.routes.draw do
  resources :events

  resources :categories

  resources :topics

  resources :projects

  devise_for :users
  root to: 'git#home'
  get '/submitting' => 'git#submitting' 
  get '/collaboration' => 'git#collaboration'
  get '/upcoming' => 'workshops#upcoming'
  get '/events' => 'events#show'

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/models/topic.rb
class Topic < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # before_action :authenticate_user!
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @category }
      else
        format.html { render action: 'new' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
  end
end

app/controllers/git_controller.rb
class GitController < ApplicationController
  def home

    
  end
  def submitting
  end
  def collaboration
  end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :deadline)
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render action: 'show', status: :created, location: @topic }
      else
        format.html { render action: 'new' }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:name, :description)
    end
end

app/controllers/workshops_controller.rb
class WorkshopsController < ApplicationController
  def upcoming
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Here</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.description %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<br>
<br>
<br>
<br>

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

<br>
<br>
LMS

app/views/events/index.html.erb
Hello, here we are

app/views/git/collaboration.html.erb
The first important thing to understand about Git is that it thinks about version control very differently than Subversion or Perforce or whatever SCM you may be used to. It is often easier to learn Git by trying to forget your assumptions about how version control works and try to think about it in the Git way.

Let's start from scratch. Assume you are designing a new source code management system. How did you do basic version control before you used a tool for it? Chances are that you simply copied your project directory to save what it looked like at that point.

 $ cp -R project project.bak 
That way, you can easily revert files that get messed up later, or see what you have changed by comparing what the project looks like now to what it looked like when you copied it.

If you are really paranoid, you may do this often, maybe putting the date in the name of the backup:

 $ cp -R project project.2010-06-01.bak 
In that case, you may have a bunch of snapshots of your project that you can compare and inspect from. You can even use this model to fairly effectively share changes with someone. If you zip up your project at a known state and put it on your website, other developers can download that, change it and send you a patch pretty easily.

 $ wget http://example.com/project.2010-06-01.zip
 $ unzip project.2010-06-01.zip
 $ cp -R project.2010-06-01 project-my-copy
 $ cd project-my-copy
 $ (change something)
 $ diff project-my-copy project.2010-06-01 > change.patch
 $ (email change.patch)

app/views/git/home.html.erb
# homepage for git command

app/views/git/submitting.html.erb
<html>
	<head>
		<title></title>
	</head>
	<body>
		<h1>
			<a href="http://git-scm.com/docs/git-add">Git-add</a><br />
			<span style="font-size:16px;"><span style="color: rgb(0, 0, 0);">(1) Manual Page</span></span></h1>
		<p>
			<span style="color:#0000ff;">NAME </span><br />
			git-add - Add file contents to the index<br />
			<br />
			<span style="color:#0000ff;">SYNOPSIS</span><br />
			git add [-n] [-v] [--force | -f] [--interactive | -i] [--patch | -p] [--edit | -e] [--[no-]all | --[no-]ignore-removal | [--update | -u]] [--intent-to-add | -N] [--refresh] [--ignore-errors] [--ignore-missing] [--] [<pathspec>...]<br />
			<br />
			<span style="color:#0000ff;">DESCRIPTION</span><br />
			This command updates the index using the current content found in the working tree, to prepare the content staged for the next commit. It typically adds the current content of existing paths as a whole, but with some options it can also be used to add content with only part of the changes made to the working tree files applied, or remove paths that do not exist in the working tree anymore. The &quot;index&quot; holds a snapshot of the content of the working tree, and it is this snapshot that is taken as the contents of the next commit. Thus after making any changes to the working directory, and before running the commit command, you must use the add command to add any new or modified files to the index. This command can be performed multiple times before a commit. It only adds the content of the specified file(s) at the time the add command is run; if you want subsequent changes included in the next commit, then you must run git add again to add the new content to the index. The git status command can be used to obtain a summary of which files have changes that are staged for the next commit. The git add command will not add ignored files by default. If any ignored files were explicitly specified on the command line, git add will fail with a list of ignored files. Ignored files reached by directory recursion or filename globbing performed by Git (quote your globs before the shell) will be silently ignored. The git add command can be used to add ignored files with the -f (force) option. Please see git-commit(1) for alternative ways to add content to a commit.</pathspec></p>
	</body>
</html>

app/views/git/test.html.erb
This is a test

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CuriousRailsGirls</title>
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap.css" />
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap-theme.css" />
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "curiousrailsgirls", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if notice %>
  <p class="alert alert-notice"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-error"><%= alert %></p>
<% end %>

<div class="container">
  <%= yield %>
</div>
<footer>
  <div class="container">
    developed by curiousrailsgirls & lisamschachtschneider
  </div>
</footer>
<script src="//railsgirls.com/assets/bootstrap.js"></script>
</body>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/submitting">Git-add Manual Page</a>
      <ul class="nav navbar-nav">
        <li class="active"><a href="/upcoming">Upcoming Workshops</a></li>
      </ul>
      <ul><%= link_to 'Topics', topics_path %></ul>
      <ul><%= link_to 'Projects', projects_path %></ul>
      <ul><%= link_to 'Categories', categories_path %></ul>
    </div>

    <p class="navbar-text pull-right">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email.rpartition('@')[0] %></strong>
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
  </div>
</nav>

</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :deadline %><br>
    <%= f.datetime_select :deadline %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Deadline</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.description %></td>
        <td><%= project.deadline %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @project.deadline %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<h1>Listing topics</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= topic.name %></td>
        <td><%= topic.description %></td>
        <td><%= link_to 'Show', topic %></td>
        <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
        <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Topic', new_topic_path %>

app/views/topics/new.html.erb
<h1>New topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @topic.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @topic.description %>
</p>

<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>

app/views/workshops/upcoming.html.erb
<div class="Workshops">
	<h2>Getting Started with Programming 2: Basics of MVC, databases, templates and CSS</h2>
	<p>After you learn how to manage your code we will teach you how to actually do something useful. </p> <p>Everyone knows already that Rails is built upon MVC but what is that exactly and what does it mean for you- well, you will find out that in this workshop! </p> <p>But we won't just cover MVC, you will also learn how to make your page look pretty and attractive! ;) and yes, we will introduce you to databases as well.</p> <p>In this workshop, you will start building your very own Personal Page application</p> <p>After this workshop, you will be able to share your Personal Page with whoever you want! ;) </p> <p>Maybe it gives you an internship on some Rails project! …you never know!</p> <p>


<b>Programme</b></p> <p>11h: start workshop</p> <p>13hish: Lunch break</p> <p>14h: Free time for questions, working on your own projects etc.</p>
	<p><strong>Date</strong><br />
	  <time datetime="2014-03-23T10:00:00+00:00">March 23, 2014 10:00</time>
	</p>
	<p class="signup">
		<a href="http://www.meetup.com/RailsGirls-NL/events/162770982/" target="_blank">Signup</a>
	</p>
</div><div class="meetup">
	<h2>Getting Started with Programming 3: Associations &amp; Javascript</h2>
	<p>This workshop will introduce you to the database/models associations and how to use them in building up comments and likes for your Personal Page project. </p> <p>To spice things up we will add some Javascript stuff and by the end of this session we will discuss possible ideas for your projects (if you have any) or we will imagine a super cool project to build data model for it. </p> <p>After this workshop you are already a pro, hehe, or at least you have a good base to see what you would like to do next! ;)</p> <p>


<b>Programme</b></p> <p>11h: start workshop</p> <p>13hish: Lunch break</p> <p>14h: Free time to ask questions, experiment, imagine your own project, etcetera</p>
	<p><strong>Date</strong><br />
	  <time datetime="2014-04-13T09:00:00+00:00">April 13, 2014 09:00</time>
	</p>
	<p class="signup">
		<a href="http://www.meetup.com/RailsGirls-NL/events/162771212/" target="_blank">Signup</a>
	</p>
</div><div class="meetup">
	<h2>Getting Started with Programming 4: Testing</h2>
	<p>When collaborating on Rails projects it is very important that when you update some code you don't break the existing code built by someone else- that is why we like to write tests!</p> <p>…and Rails makes it super easy for us! </p> <p>This will be the workshop when two coaches will do a live demo for you! </p> <p>Real pair programming, guided by TDD (test driven development). </p> <p>No worries, you won't be just watching it- we will prepare a challenge for you as well! </p> <p>We will cover unit and integration tests. </p> <p>This workshop will you give you an idea how the real pros do things!</p> <p>


<b>Programme</b></p> <p>11h: Start workshop</p> <p>13hish: Lunch break</p> <p>14h: Free time to work on your personal projects, ask questions, experiment, etcetera</p>
	<p><strong>Date</strong><br />
	  <time datetime="2014-05-25T09:00:00+00:00">May 25, 2014 09:00</time>
	</p>
	<p class="signup">
		<a href="http://www.meetup.com/RailsGirls-NL/events/162771332/" target="_blank">Signup</a>
	</p>
</div><div class="meetup">
	<h2>Getting Started with Programming 5: Working on your personal project</h2>
	<p>The last workshop before the summer will be focused on crafting things yourself.</p> <p>Coaches will be available to help you out if you need advice or guidance.</p> <p>Considering you have been following previous workshops, this one will be yet another day having fun coding and hanging around people that like to do the same! </p> <p>…and you can help us prepare a real <i><b>hackaton</b></i>!</p>
	<p><strong>Date</strong><br />
	  <time datetime="2014-06-22T09:00:00+00:00">June 22, 2014 09:00</time>
	</p>
	<p class="signup">
		<a href="http://www.meetup.com/RailsGirls-NL/events/162771402/" target="_blank">Signup</a>
	</p>
</div>